Create a plain JavaScript with objects
mirelapitt/Awesome-books pull request #1
Opened 2022-05-30 08:54 UTC by mirelapitt

On this pull request, we created a plain JavaScript with objects using JavaScript objects and arrays. We also needed to dynamically modify the DOM and add some basic events.

2022-05-30 15:11 UTC, AnselemOdims requested changes
### Hi team, 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:

## Required Changes ♻️
- [ ] As this is supposed to be a collaborative project, please ensure that there is contribution from each of member of the team.
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-30 15:11 UTC, AnselemOdims commented on app.js
> +  displayBooks();
- [ ] [OPTIONAL] It will be better for you to use methods like `concat, filter, slice` that don't mutate the state of the array instead of `splice`

2022-05-31 02:12 UTC, BenMukebo approved these changes
### Hi Team, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] Please let's make sure that contributions to a group project are distributed equally among the members (commit messages should be fairly equal). 💯 👍🏻 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 02:12 UTC, BenMukebo commented on app.js
> +  displayBooks();
- [ OPTIONAL] Kindly make sure to address the requested changes 😉 💯

2022-05-31 03:47 UTC, merged